MvcCoreCv/Controllers/HobbyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcCoreCv.Entities;
using MvcCoreCv.Repositories;
using MvcCoreCv.Repositories.Abstract;

namespace MvcCoreCv.Controllers
{
    
    public class HobbyController : Controller
    {
        private readonly IHobbyRepository _repo;

        public HobbyController(IHobbyRepository repo)
        {
            _repo = repo;
        }
       

        public IActionResult Index()
        {
            try
            {
                return View(_repo.GetAll());
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("Index");               
            }
            
        }
        public IActionResult DeleteHobby(int id) 
        {
            try
            {
                var deletedValue = _repo.GetById(id);
                _repo.Delete(deletedValue);
                TempData["status"] = "Veri silme başarılı";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
        
        [HttpGet]
        public IActionResult UpdateHobby(int id)
        {
            return View(_repo.GetById(id));

        }
        [HttpPost]
        public IActionResult UpdateHobby(TblHobby p)
        {
            try
            {
                _repo.Update(p);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("Index");
            }            
        }
        [HttpGet]
        public IActionResult AddHobby()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddHobby(TblHobby p)
        {
            try
            {
                _repo.Create(p);
                TempData["status"] = "Ekleme işlemi Başarılı...";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("Index");
            }            
        }
    }
}

MvcCoreCv/Views/Hobby/AddHobby.cshtml
@using MvcCoreCv.Entities
@model TblHobby
@{
    ViewData["Title"] = "AddHobby";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>AddHobby</h1>

<form class="form-group" method="post">
    <input type="text" asp-for="Description" class="form-control" placeholder="Hobi Başlık giriniz." />
    <br />
    <input type="text" asp-for="Description2" class="form-control" placeholder="Hobi içerik giriniz." />
    <br />

    <button class="btn btn-info">Ekle</button>
</form>

MvcCoreCv/Views/Hobby/Index.cshtml
@using MvcCoreCv.Entities
@model List<TblHobby>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<body class="hold-transition sidebar-mini">

    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Hobilerim</h1>
          </div>
         
        </div>
      </div><!-- /.container-fluid -->
    </section>
     
    <!-- Main content -->
    <section class="content">
        
        <div class="row">            
            <div class="col-12" id="accordion">
                <a asp-action="AddHobby" asp-controller="Hobby" class="btn btn-info">Ekle</a>
        <br />
                @foreach (var item in Model)
        {
                    <div class="card card-primary card-outline">
                        <a class="d-block w-100" data-toggle="collapse" href="#aa-@item.Id">
                            <div class="card-header">
                                <h4 class="card-title w-100">
                                    @item.Description
                                </h4>
                            </div>
                        </a>
                        <div id="aa-@item.Id" class="collapse" data-parent="#accordion">
                            <div class="card-body">
                                @item.Description2
                                <br>
                            <a asp-action="DeleteHobby" asp-controller="Hobby" asp-route-id="@item.Id" class="btn btn-info" onclick="return confirm('Silme işlemi onaylansın mı?')">Sil</a> 
                                <a asp-action="UpdateHobby" asp-controller="Hobby" asp-route-id="@item.Id" class="btn btn-info">Güncelle</a>
                            </div>
                        </div>
                    </div>

        }
            </div>
       </div>
       
    </section>
    <!-- /.content -->

  <!-- /.content-wrapper -->

 

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

<!-- ./wrapper -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>
</body>
</html>

    
    
    

MvcCoreCv/Views/Hobby/UpdateHobby.cshtml
@using MvcCoreCv.Entities
@model TblHobby
@{
    ViewData["Title"] = "UpdateHobby";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>UpdateHobby</h1>

<form class="form-group" method="post">
    <input type="text" asp-for="Description" class="form-control" placeholder="Hobi Başlık giriniz." />
    <br />
    <input type="text" asp-for="Description2" class="form-control" placeholder="Hobi içerik giriniz." />
    <br />    
    
    <button class="btn btn-info">Güncelle</button>
</form>